cc_binary(
    name = "hcc",
    srcs = ["main.cpp"],
    deps = [
        "//lib:Graph",
        "//lib:NAO",
        "//lib:IndexBasedCorrelationClustering",
        "//lib:NaiveCorrelationClustering",
    ]
)
